alter sequence technology_entity_id_seq restart with 1;
insert into technology_entity (title) values ('Flutter');
insert into technology_entity (title) values ('TypeORM');
insert into technology_entity (title) values ('WebGL');
insert into technology_entity (title) values ('2d Canvas');
insert into technology_entity (title) values ('Tailwind');
insert into technology_entity (title) values ('Spring Webflux');
insert into technology_entity (title) values ('Kafka');
insert into technology_entity (title) values ('MongoDB');
insert into technology_entity (title) values ('MikroORM');
insert into technology_entity (title) values ('Docker');
insert into technology_entity (title) values ('Github');
insert into technology_entity (title) values ('jQuery');
insert into technology_entity (title) values ('Java');
insert into technology_entity (title) values ('Sass');
insert into technology_entity (title) values ('PostgreSQL');
insert into technology_entity (title) values ('GitHub Pages');
insert into technology_entity (title) values ('TypeScript');
insert into technology_entity (title) values ('React');
insert into technology_entity (title) values ('Redux');
insert into technology_entity (title) values ('Android');
insert into technology_entity (title) values ('Express');
insert into technology_entity (title) values ('Django');
insert into technology_entity (title) values ('Next.js');
insert into technology_entity (title) values ('Heroku');
insert into technology_entity (title) values ('Gatsby');
insert into technology_entity (title) values ('styled-components');
insert into technology_entity (title) values ('Chakra UI');
insert into technology_entity (title) values ('Python');
insert into technology_entity (title) values ('Cloud Run');
insert into technology_entity (title) values ('Javascript');
insert into technology_entity (title) values ('Redis');
insert into technology_entity (title) values ('Apollo');
insert into technology_entity (title) values ('Urql');
insert into technology_entity (title) values ('Node');
insert into technology_entity (title) values ('TypeGraphQL');
insert into technology_entity (title) values ('GraphQL'); 
insert into technology_entity (title) values ('SQL');
insert into technology_entity (title) values ('Google Play');
insert into technology_entity (title) values ('Three.js');
insert into technology_entity (title) values ('React Three Fiber');
insert into technology_entity (title) values ('Go');
insert into technology_entity (title) values ('Vercel');
insert into technology_entity (title) values ('Netlify');
insert into technology_entity (title) values ('GLSL');
insert into technology_entity (title) values ('Graphene-Python');
insert into technology_entity (title) values ('Cypress');
insert into technology_entity (title) values ('React Testing Library');
insert into technology_entity (title) values ('Jest');
insert into technology_entity (title) values ('Kotlin');
insert into technology_entity (title) values ('Web Assembly');
insert into technology_entity (title) values ('Rust');
insert into technology_entity (title) values ('Dart');


